version: '3.8'

services:
  app:
    build:
      context: ./app   # Laravel lives here
      dockerfile: ../Dockerfile
    container_name: laravel_app
    working_dir: /var/www
    volumes:
      - ./app:/var/www
    depends_on:
      - postgres
    networks:
      - laravel

  postgres:
    image: postgres:14
    container_name: pgsql
    restart: unless-stopped
    environment:
      POSTGRES_DB: warehouse_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - laravel

  nginx:
    image: nginx:alpine
    container_name: laravel_nginx
    ports:
      - "8000:80"
    volumes:
      - ./app:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    networks:
      - laravel

volumes:
  pgdata:

networks:
  laravel:
